name: ruminate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  get: ^4.3.0
  image: ^3.0.2
  path_provider: ^2.0.1
  sliding_up_panel: 2.0.0+1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  dart_vlc: ^0.1.0
  flutter: 
    sdk: flutter
    
#################################
#######Dev Dependencies##########
#################################
dev_dependencies: 
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
  flutter_native_splash: ^1.1.8+4
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icon.png

flutter_native_splash: 
  color: '#000000'
  image: assets/icon.png

